LIB_A = ./1-5-15-tst/
LIB_B =	./1-15-25-tst/
LIB_C =	./1-35-45-tst/
LIB_D =	./5-5-15-tst/
LIB_E =	./5-15-25-tst/
LIB_F =	./5-35-45-tst/
LIB_G =	./10-5-15-tst/
LIB_H =	./10-15-25-tst/
LIB_I =	./10-35-45-tst/

all:
	(cd $(LIB_A);make micaz sim)
	(cd $(LIB_B);make micaz sim)
	(cd $(LIB_C);make micaz sim)
	(cd $(LIB_D);make micaz sim)
	(cd $(LIB_E);make micaz sim)
	(cd $(LIB_F);make micaz sim)
	(cd $(LIB_G);make micaz sim)
	(cd $(LIB_H);make micaz sim)
	(cd $(LIB_I);make micaz sim)
